name: Go Tests

on:
  push:
    branches:
      - main  # Run tests when changes are pushed to the 'main' branch
  pull_request:
    branches:
      - main  # Run tests for pull requests targeting the 'main' branch
  release:
    types:
      - created  # Run tests when a new release is created

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.0

      - name: Run tests
        run: |
          go test ./...  -test.skip TestLookupCompound -v  # Run all tests in verbose mode